# Generated by Django 3.1.3 on 2021-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
